// <auto-generated />
using MachineAccounting.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MachineAccounting.DataContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180619152456_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Currency");

                    b.Property<int>("MachineTypeId");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("Rest");

                    b.Property<int>("StorageId");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("StorageId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.MachineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("SectionId");

                    b.Property<int?>("StorageId");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("StorageId");

                    b.ToTable("MachineType");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("MachineId");

                    b.Property<string>("Name");

                    b.Property<int>("StorageId");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("StorageId");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Machine", b =>
                {
                    b.HasOne("MachineAccounting.DataContext.Models.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MachineAccounting.DataContext.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.MachineType", b =>
                {
                    b.HasOne("MachineAccounting.DataContext.Models.Section", "Section")
                        .WithMany("MachineTypes")
                        .HasForeignKey("SectionId");

                    b.HasOne("MachineAccounting.DataContext.Models.Storage")
                        .WithMany("MachineTypes")
                        .HasForeignKey("StorageId");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Request", b =>
                {
                    b.HasOne("MachineAccounting.DataContext.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MachineAccounting.DataContext.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
