// <auto-generated />
using System;
using MachineAccounting.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MachineAccounting.DataContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180620154339_UpdateDelete")]
    partial class UpdateDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Currency");

                    b.Property<bool>("Deleted");

                    b.Property<int>("MachineTypeId");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("Rest");

                    b.Property<int>("StorageId");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("StorageId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.MachineOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count");

                    b.Property<string>("Description");

                    b.Property<int>("MachineId");

                    b.Property<int>("OrderId");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OrderId");

                    b.ToTable("MachineOrder");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.MachineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("SectionId");

                    b.Property<int?>("StorageId");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("StorageId");

                    b.ToTable("MachineType");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("OrderType");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.Machine", b =>
                {
                    b.HasOne("MachineAccounting.DataContext.Models.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MachineAccounting.DataContext.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.MachineOrder", b =>
                {
                    b.HasOne("MachineAccounting.DataContext.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MachineAccounting.DataContext.Models.Order", "Order")
                        .WithMany("MachineOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MachineAccounting.DataContext.Models.MachineType", b =>
                {
                    b.HasOne("MachineAccounting.DataContext.Models.Section", "Section")
                        .WithMany("MachineTypes")
                        .HasForeignKey("SectionId");

                    b.HasOne("MachineAccounting.DataContext.Models.Storage")
                        .WithMany("MachineTypes")
                        .HasForeignKey("StorageId");
                });
#pragma warning restore 612, 618
        }
    }
}
